spring.application.name=hotel_management_backend

spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=!m@g!n@ti@n
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# generate a 256-bit secret and base64 it; never commit real secrets
security.jwt.secret-base64=8B9y1l6yTz9r5F5qS0pZcLk3wqP0W3b6M6Hq1vK0Lk8=
security.jwt.access-ttl-ms=3600000